export const SET_SITE_LIST = "SET_SITE_LIST";

export const GET_HEADER_CURRENTSITE = "GET_HEADER_CURRENTSITE";

export const SET_HEADER_CURRENTSITE = "SET_HEADER_CURRENTSITE";

export const SET_HEADER_CURRENTSITEID = "SET_HEADER_CURRENTSITEID";



//更新 侧边栏 模式
export const UPDATE_LEFTBAR_TYPE = "UPDATE_LEFTBAR_TYPE";



